In [2]:
import numpy as np

Задача 1

In [3]:
A = np.matrix([[1,2,1],[-2,1,1]])
B = np.matrix([[3,1],[-1,0],[2,4]])
C = np.matrix([[-2,2],[1,-1],[1,2]])
A = np.transpose(A)

In [ ]:
A+2*B

matrix([[7, 0],
        [0, 1],
        [5, 9]])

In [ ]:
B+2*C

matrix([[-1,  5],
        [ 1, -2],
        [ 4,  8]])

Задача 2

In [ ]:
A = np.zeros((8,8),dtype=int)
A[1::2,::2]=1
A[::2,1::2]=1

In [ ]:
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задача 3

In [4]:
A = np.arange(start=0, stop=1.5, step=0.1)
B = np.arange(start=1, stop=7, step=1)
print(A)
print(B)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
[1 2 3 4 5 6]


In [5]:
A = np.matrix(A.reshape(5,3))
B = np.matrix(B.reshape(3,2))
print(A)
print(B)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]


In [6]:
A*B

matrix([[ 1.3,  1.6],
        [ 4. ,  5.2],
        [ 6.7,  8.8],
        [ 9.4, 12.4],
        [12.1, 16. ]])

Задача 4

In [ ]:
A = np.arange(start=1, stop=72, step=2)
print(A)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]


In [ ]:
A = np.arange(start=3, stop=72, step=3)
print(A)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69]
